# Generated by Django 4.2.5 on 2023-11-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('User_Type', models.CharField(max_length=20)),
                ('Profile_Picture', models.ImageField(upload_to='media/profile_pic')),
                ('User_Name', models.CharField(max_length=50)),
                ('Email_Id', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=100)),
            ],
        ),
    ]
