# Generated by Django 4.2.5 on 2023-11-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Profile_Picture',
            field=models.ImageField(upload_to='media/Profile_Picture'),
        ),
    ]
