# Generated by Django 4.2.5 on 2023-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_signup_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
